apiVersion: v1
kind: Service
metadata:
  name: npr-db-redis
  labels:
    app: npr-db
spec:
  selector:
    app: npr-db
  ports:
  - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npr-db-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npr-db
  template:
    metadata:
      labels:
        app: npr-db
    spec:
      containers:
      - name: npr-db-redis
        image: csampson/npr-db-redis:latest
        ports:
          - containerPort: 6379
