openapi: 3.0.0
info:
  version: 'v1.0.0'
  title: 'npr-db'
paths:
  /stations:
    get:
      summary: 'List all stations'
      responses:
        '200':
          description: Returns basic information about all NPR member stations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /stations/:id:
    get:
      summary: 'Fetch a specific station'
      responses:
        '200':
          description: Returns detailed information about a specific member station
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationDetails'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    StationIndex:
      type: object
      properties:
        band:
          type: string
          enum: ['am', 'fm']
        callsign:
          type: string
        frequency:
          type: number
        geolocation:
          type: string
        id:
          type: string
        market_city:
          type: string
        market_state:
          type: string
      required:
        - band
        - callsign
        - frequency
        - id
    StationList:
      type: array
      items:
        $ref: '#/components/schemas/StationIndex'
    StationDetails:
      allOf:
        - $ref: '#/components/schemas/StationIndex'
        - type: object
      properties:
        address:
          type: string
        fax:
          type: integer
          format: int64
        links:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/BrandLink'
        logo:
          type: string
        name:
          type: string
        phone:
          type: integer
          format: int64
        phone_extension:
          type: integer
          format: int32
        tagline:
          type: string
      required:
        - address
        - links
        - logo
        - name
    BrandLink:
      type: object
      properties:
        rel:
          type: string
          enum: ['homepage', 'logo', 'small_logo', 'hello_id_audio', 'station_message_audio', 'facebook', 'twitter']
        href:
          type: string
        content_type:
          type: string
    DonationLink:
      type: object
      properties:
        href:
          type: string
        title:
          type: string
        rel:
          type: string
          enum: [ 'pledge_page', 'station_npr_one_pledge_page', 'station_thank_you_audio', 'station_pledge_audio']
      required:
        - href
        - rel
    PodcastLink:
      type: object
      properties:
        href:
          type: string
        title:
          type: string
    StreamLink:
      type: object
      properties:
        href:
          type: string
        is_primary_stream:
          type: boolean
        title:
          type: string
        type:
          type: string
          enum: ['audio_mp3_stream', 'audio_aac_stream']
      required:
        - href
        - is_primary_stream
        - type
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string